### ISSUE TITLE
How to configure the dataset?

### ISSUE THREAD

**Issue by jayurbain** [Janspiry/Palette-Image-to-Image-Diffusion-Models#1]
Thanks for putting together this software. Can you provide some direction for how to create a dataset for train and test for image inpainting?

In the configuration file I see references to *.flist file. I assume this is a text list of images to use for testing. But I'm not sure how to create it and format it.

Thanks,
Jay

**Comment by Janspiry** [comment]
Hi, thanks for your attention. 
We use the default division of these datasets for training and evaluation, and  *.flist just list their names for fast loading. I will update it soon.
