### ISSUE TITLE
NotImplementedError: Dataset [InpaintDataset() form data.dataset] not recognized.

### ISSUE THREAD

**Issue by tuotuoalan** [Janspiry/Palette-Image-to-Image-Diffusion-Models#105]
I have modified the dataset path, but I am still encountering this issue.
![image](https://github.com/user-attachments/assets/e4fc297e-c24c-45b5-b214-9d208d048282)
![image](https://github.com/user-attachments/assets/781a7d23-a9ef-4e4b-b7c0-18225a278a43)
![image](https://github.com/user-attachments/assets/6841b16a-e281-40b0-8d7e-f0862c706231)
![image](https://github.com/user-attachments/assets/a8976a4c-0531-4729-970b-396d16031229)

**Comment by PeterHUistyping** [comment]
I met the same issue after updating the correct dataset path.  Through debugging into the `InpaintDataset()` class with breakpoint, the issue stems from 
```
images = [i for i in np.genfromtxt(dir, dtype=np.str, encoding='utf-8')]
```

The dtype `np.str` is deprecated, hence it is better to use `np.str_` instead.
