### ISSUE TITLE
Uncrop right side only

### ISSUE THREAD

**Issue by megaluck** [Janspiry/Palette-Image-to-Image-Diffusion-Models#11]
Is there any way to set to uncrop on the right side of the pictures only ?

**Comment by Janspiry** [comment]
Yes, you can modify the configure file https://github.com/Janspiry/Palette-Image-to-Image-Diffusion-Models/blob/d1b9b010edeee177aaa15850002766e370a8307b/config/uncropping_places2.json#L53 to point out the bbox https://github.com/Janspiry/Palette-Image-to-Image-Diffusion-Models/blob/d1b9b010edeee177aaa15850002766e370a8307b/data/dataset.py#L130
