### ISSUE TITLE
mask_img = img*(1 - mask) + mask ValueError: operands could not be broadcast together with shapes (3,256,256) (256,256,1)

### ISSUE THREAD

**Issue by DanBigioi** [Janspiry/Palette-Image-to-Image-Diffusion-Models#15]
In dataset.py, the get mask function returns a mask of shape of (h, w, 1).

When the img is opened by PIL, and passed through the transform, self.tfs = transforms.Compose([ 

The toTensor transform changes the image shape from H,W,C to C,H,W. 

When I try to calculate the mask image by doing mask_img = img*(1 - mask) + mask, I get the value error above. Should the image transform be returning the image in the form (C,H,W)?

This is my code:

```python

tfs = transforms.Compose([
                transforms.Resize((256, 256)),
                transforms.ToTensor(),
                transforms.Normalize(mean=[0.5, 0.5, 0.5], std=[0.5,0.5, 0.5])
        ])

from PIL import Image
img = Image.open("C:/Users/Documents/Obama_256x256.jpg").convert('RGB')
img = tfs(img)

mask = face_mask((256,256), landmark_list) #returns facemask of shape (h,w,1)
#mask = np.swapaxes(mask, -1, 0)
mask_img = img*(1 - mask) + mask

```

**Comment by Janspiry** [comment]
![image](https://user-images.githubusercontent.com/32922494/171841714-90a014de-cade-4b01-8492-7ed65df1303c.png)
