### ISSUE TITLE
Dockerfile example

### ISSUE THREAD

**Issue by trufty** [Janspiry/Palette-Image-to-Image-Diffusion-Models#18]
Dockerfile that works for me if anyone's interested.
```
FROM nvidia/cuda:11.0.3-devel-ubuntu20.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && \
    apt-get install python3 -y && \
    apt-get install python3-pip -y && \
	apt-get install git ffmpeg libsm6 libxext6 -y

RUN cd ./home && \
	git clone https://github.com/Janspiry/Palette-Image-to-Image-Diffusion-Models
#I only clone this for the requirements.txt.  I run palette from mounted drive /root/data

RUN pip3 install \
	torch==1.7.0+cu110 \
	torchvision==0.8.1+cu110 \ 
	-f https://download.pytorch.org/whl/torch_stable.html

RUN pip3 install -r ./home/Palette-Image-to-Image-Diffusion-Models/requirements.txt
	
WORKDIR ./root/data
```

Run with something like
```
docker run --rm --gpus all -it -v <path_to_palette_repo>:/root/data -v palette
```

**Comment by sgbaird** [comment]
@trufty so do you manually clone a copy of the repo to `./root/data`? Haven't used docker much, but interested in getting this running. Having trouble with other installation methods #20 #21 #22.

**Comment by sgbaird** [comment]
@trufty thanks! I will probably give this a try at some point.

**Comment by Janspiry** [comment]
Feel free to reopen the issue if there is any question

**Comment by sgbaird** [comment]
@Janspiry can you make it so people can reproducibly use your code? For example, add unit tests integrated with GitHub actions.

**Comment by Janspiry** [comment]
That's good advice, but need some time.
Considering that other users can work well, I think there is a bias in the operation.
