### ISSUE TITLE
My installation instructions for conda

### ISSUE THREAD

**Issue by sgbaird** [Janspiry/Palette-Image-to-Image-Diffusion-Models#20]
## conda
```bash
conda create -n palette python==3.9.*
conda activate palette
conda install pytorch:pytorch pytorch:torchvision pytorch:cudatoolkit=11.3 numpy pandas tqdm scipy tensorboardx
```
(though `mamba install` preferred, especially if you get a dependency conflict)

For pytorch installation commands, see https://pytorch.org/get-started/locally/

##
then install the leftover pip dependencies:
```
pip install opencv-python clean-fid
```
Note that `opencv` had a conflict due to blas or something, which came up very quickly by trying to `mamba` install. Couldn't find an Anaconda distribution of `clean-fid`.

**Comment by sgbaird** [comment]
See also https://github.com/Janspiry/Palette-Image-to-Image-Diffusion-Models/issues/18

**Comment by Janspiry** [comment]
Feel free to reopen the issue if there is any question
