### ISSUE TITLE
What is the exact role of strict?

### ISSUE THREAD

**Issue by imesu2378** [Janspiry/Palette-Image-to-Image-Diffusion-Models#23]
Hi I was trying out the test process with the provided pretrained models. But the load_networks function in the model.py file doesn't seem work with strict=True
I get the error message below
![image](https://user-images.githubusercontent.com/73635769/173525383-65469af2-a36a-4d82-ade8-37e84a8570fa.png)

The model is loaded properly with strict=False and the inpainting also seems to work fine
![image](https://user-images.githubusercontent.com/73635769/173525318-1f5a403c-52ce-4d46-a849-631331b3bf18.png)
![Out_25532](https://user-images.githubusercontent.com/73635769/173525799-083a0eb1-3b8d-4cd3-8cb9-48d79076970b.jpg)

By the way you mentioned that a small dataset was enough for face inpainting but a much larger dataset was required for more complex scene inpainting like the places2 dataset.
I'm currently working on a image to image conditional diffusion model for driving scenes and a dataset of 10k samples doesn't seem to converge at all. Do you think that this is due to the small dataset? I'm curious of how much portion of the 10 million samples were used to train your model from the places2 dataset.

Thanks a bunch.

**Comment by Janspiry** [comment]
Thanks for your attention. 
1. In palces2, we use the default training dataset, and train.flist can be found in provided google drive. 
![image](https://user-images.githubusercontent.com/32922494/173738273-05f26d10-0d06-49f1-8890-ba4e0a25a364.png)
2. strict is for debug.

**Comment by bronyayang** [comment]
@imesu2378 I am also training the model on the driving scene dataset. Could the divergence issue be caused by hyperparameter?

**Comment by Janspiry** [comment]
Feel free to reopen the issue if there is any question
