### ISSUE TITLE
inference results with noise

### ISSUE THREAD

**Issue by winnechan** [Janspiry/Palette-Image-to-Image-Diffusion-Models#24]
Hi, thanks for your excellent project !

I am new to diffusion model. Recently, I have trained a colorization model with this code and a dataset with 64 images for 1000 epoches (where the mse loss is quiet small). The inference results with the trained model are still with noise. I am wondering is this because the short training time or the small dataset hard to cover the space of random noise ? Can I leverage some tricks to fix it ? 

Appreciate any help !

**Comment by Janspiry** [comment]
Hi, thanks for your attention.
The problem is the same as #17

**Comment by winnechan** [comment]
@Janspiry Thanks for the comment. Actually, my dataset contains only objects of the same class, the results look like that the Gaussion noise is not removed completely. Is the problem still the same to https://github.com/Janspiry/Palette-Image-to-Image-Diffusion-Models/issues/17 ? Maybe I should try training for a longer time at first.

**Comment by winnechan** [comment]
@Janspiry Yes, training hyperparameter is the reason ! I have trained the model with 2000 more epoches (10k iterations at total) and the noises disappear. So, the training and inference time of diffusion model are much longer than that of GAN but with better stability and visual quality ?

**Comment by Janspiry** [comment]
Feel free to reopen the issue if there is any question.

**Comment by xunguangwang** [comment]
Hi, how to solve this problem? My generated images are too noisy.
