### ISSUE TITLE
Unet input channels number for colorization

### ISSUE THREAD

**Issue by fColangelo** [Janspiry/Palette-Image-to-Image-Diffusion-Models#25]
Hi and thanks for the repo!

I have a question concerning the input dims of the Unet for colorization. If I understand correctly, the Unet is fed a 6 channel image containing noise and a 3-channel version of the black and white image as conditioning. 
Is there an advantage in doing this compared to using a 1-channel black and white image as conditioning, given that the network would require less memory?
Is the conditioning less effective if only 1 channel is given?
thanks!

**Comment by Janspiry** [comment]
I think this is the better choice, the 6 channels are just to follow the paper elaboration.
![image](https://user-images.githubusercontent.com/32922494/175776459-1e0c4209-53dc-4cf6-8fcc-cb5a93ea9a68.png)

**Comment by fColangelo** [comment]
I see, thank you for your comment! Would you mind commenting on other possible approaches for conditioning that you think are valid. The paper is not really clear on how to give the conditioning image x as input.

**Comment by xenova** [comment]
@fColangelo I had the exact same question! Thanks for bringing it up. Could you maybe explain how you changed the code to account for this? Thanks!

**Comment by Janspiry** [comment]
> I see, thank you for your comment! Would you mind commenting on other possible approaches for conditioning that you think are valid. The paper is not really clear on how to give the conditioning image x as input.

Yes. Follow what they did before and just concatenate the channels, and you can try 1 channel and 3 channels.

**Comment by Janspiry** [comment]
Feel free to reopen the issue if there is any question.
