### ISSUE TITLE
Question about calculating metrics

### ISSUE THREAD

**Issue by xenova** [Janspiry/Palette-Image-to-Image-Diffusion-Models#28]
When calculating metrics, why are you comparing the input (conditional) image with the generated image? Shouldn't we compare the output with the ground truth image?

https://github.com/Janspiry/Palette-Image-to-Image-Diffusion-Models/blob/feca17c50dabfcb8f51ed26df881ce227212904a/models/model.py#L166-L187

In particular:
https://github.com/Janspiry/Palette-Image-to-Image-Diffusion-Models/blob/feca17c50dabfcb8f51ed26df881ce227212904a/models/model.py#L185

**Comment by Janspiry** [comment]
Thank you for pointing out this error, I'll fix it asap.
