### ISSUE TITLE
README: guide on non-CLI usage, i.e. directly using Python functions, for non-image application

### ISSUE THREAD

**Issue by sgbaird** [Janspiry/Palette-Image-to-Image-Diffusion-Models#3]
In particular, I'm interesting in using a custom dataset for an application not involving images directly, but with a similar structure to images (square matrices with channels).

Related: https://github.com/Janspiry/Palette-Image-to-Image-Diffusion-Models/issues/1

**Comment by Janspiry** [comment]
Thanks for the suggestion, but I don't have the time to do so at the moment.
