### ISSUE TITLE
Maximum resolution for inference

### ISSUE THREAD

**Issue by mahdip72** [Janspiry/Palette-Image-to-Image-Diffusion-Models#30]
Is there any limitation for inferencing with higher resolution??
If the answer is no, does the model perform well on higher resolution such as 1024×1024 or more for in-painting?

**Comment by Janspiry** [comment]
Sorry for this question. limited by CUDA memory, I have not tried higher resolution.

**Comment by Janspiry** [comment]
Feel free to reopen the issue if there is any question.
