### ISSUE TITLE
Multi-task learning pretrained models

### ISSUE THREAD

**Issue by eliahuhorwitz** [Janspiry/Palette-Image-to-Image-Diffusion-Models#38]
Hey,
Thank you for the implementations! 
Are there any plans on releasing a pretrained version on the multi-task learning objective (section 5.7 in the paper)?

Thanks,
Eliahu

**Comment by Janspiry** [comment]
Sorry, Eliahu. I don't have time to try it for now.

**Comment by eliahuhorwitz** [comment]
Thanks
