### ISSUE TITLE
How to train on custom dataset and how to train jpeg restoration model?

### ISSUE THREAD

**Issue by universewill** [Janspiry/Palette-Image-to-Image-Diffusion-Models#39]
How to train on custom dataset and how to train jpeg restoration model?

**Comment by Janspiry** [comment]
You can follow the https://github.com/Janspiry/Palette-Image-to-Image-Diffusion-Models/blob/136b29f58d0af6e5db9f3655d2891f5a855fcdaa/data/dataset.py#L35 to rewrite your dataset and import it in the configure file.
