### ISSUE TITLE
max_period of gamma embeddings

### ISSUE THREAD

**Issue by borisdayma** [Janspiry/Palette-Image-to-Image-Diffusion-Models#4]
Hi,

I see that you use the same embeddings for gammas that are used typically for time steps.
However time steps often go from 0 to 1,000.
Should the `max_period` be updated accordingly? I'm thinking it should be lowered to something following the new order of magnitude (maybe to 10).

**Comment by Janspiry** [comment]
Hi, thanks for your advice.

I think updating the `max_period` is preferable, and the current version simply references its previous work wavegrad https://github.com/lmnt-com/wavegrad/blob/d050ab0ce01ba7676cd1e739b2fae91d9ea57144/src/wavegrad/model.py#L58. If I have time, I will try it in a later experiment. 

Thanks again for your valuable advice!
