### ISSUE TITLE
Do you have a plan of using torch.amp?

### ISSUE THREAD

**Issue by ksunho9508** [Janspiry/Palette-Image-to-Image-Diffusion-Models#40]
It took a little bit long time per epoch.
So, I want to use 'torch.amp' & DDP, but it fails with following error, 'RuntimeError: Input type (torch.cuda.HalfTensor) and weight type (torch.cuda.FloatTensor) should be the same'

Here is my code of 'models/models.py -> train_step:
      with torch.cuda.amp.autocast(enabled=self.amp):
          loss = self.netG(self.gt_image, self.cond_image, mask=self.mask)

I guess, this error caused from 'CheckpointFunction.backward', but I am not sure.

Could you add 'torch.amp' ?

**Comment by Janspiry** [comment]
Sorry, I haven't used amp and don't have time to try it for now

**Comment by ksunho9508** [comment]
@Janspiry No problem, I just adopted as below.
unet > attention block > forward
`   qkv = self.qkv(self.norm(x.float())) ` 
x -> x.float(), and then, torch amp works, half memory, twice faster

**Comment by Hikari6666** [comment]
@ksunho9508 hello，Can you tell me if you only need to make the two changes you mentioned above to use torch.amp? Thank you
