### ISSUE TITLE
GT_datasets in experiments folder missing

### ISSUE THREAD

**Issue by ruairiseosamh** [Janspiry/Palette-Image-to-Image-Diffusion-Models#41]
Hello,

So I am trying to train the model. It can train fine, but when it tries to val it can't find the GT_datasets folder in the experiments folder. Any advice on how to fix this?

Thanks,
Rory

**Comment by Janspiry** [comment]
Could you give me a detailed configure file and training log?

**Comment by ruairiseosamh** [comment]
I fixed it. I needed to use absolute paths instead of relative ones. Thanks anyways.
