### ISSUE TITLE
AssertionError: Validation set size is configured to be larger than entire dataset.

### ISSUE THREAD

**Issue by wuhongsheng** [Janspiry/Palette-Image-to-Image-Diffusion-Models#43]
I try  output error  AssertionError: Validation set size is configured to be larger than entire dataset
%cd Palette-Image-to-Image-Diffusion-Models/
!python run.py -p train -c config/inpainting_celebahq.json

**Comment by Janspiry** [comment]
That means your setting about data_len https://github.com/Janspiry/Palette-Image-to-Image-Diffusion-Models/blob/136b29f58d0af6e5db9f3655d2891f5a855fcdaa/config/inpainting_celebahq.json#L23 is larger than given dataset

**Comment by wuhongsheng** [comment]
> That means your setting about data_len
> 
> https://github.com/Janspiry/Palette-Image-to-Image-Diffusion-Models/blob/136b29f58d0af6e5db9f3655d2891f5a855fcdaa/config/inpainting_celebahq.json#L23
> 
> is larger than given dataset
I try change validation_split value output error 
 raise NotImplementedError('{} [{:s}() form {:s}] not recognized.'.format(init_type, class_name, file_name))
NotImplementedError: Network [Network() form models.network] not recognized.

**Comment by Janspiry** [comment]
Can you show the trackback and logging file?
