### ISSUE TITLE
where does the code save the output image ?

### ISSUE THREAD

**Issue by hodfa840** [Janspiry/Palette-Image-to-Image-Diffusion-Models#45]
Hello, 
Thank you for your code.
Can you help us to run it on our own dataset?

**Comment by Janspiry** [comment]
Hi, you can find code in https://github.com/Janspiry/Palette-Image-to-Image-Diffusion-Models/blob/136b29f58d0af6e5db9f3655d2891f5a855fcdaa/models/model.py#L84, which  use the function https://github.com/Janspiry/Palette-Image-to-Image-Diffusion-Models/blob/136b29f58d0af6e5db9f3655d2891f5a855fcdaa/core/util.py#L9
Others is duplicated with #39

**Comment by hodfa840** [comment]
Thank you!
