### ISSUE TITLE
running the script

### ISSUE THREAD

**Issue by hodfa840** [Janspiry/Palette-Image-to-Image-Diffusion-Models#46]
Hello,

I have tried to run your code following the guideline.
 I downloaded the celeb dataset from Kaggle in the readme file and insert it in the data folder then rename it to celeba_hq so the location of the data now is data/celeba_hq . I downloaded the flist file and insert it celeba_hq/flist. Then In  the  inpainting_celebahq.json file, I change the train data set like this:

"datasets": { // train or test
        "train": { 
            "which_dataset": {  // import designated dataset using arguments 
                "name": ["data.dataset", "InpaintDataset"], // import Dataset() class / function(not recommend) from data.dataset.py (default is [data.dataset.py])
                "args":{ // arguments to initialize dataset
                    "data_root": "data/celebahq/flist/train.flist",
                    "data_len": -1,
                    "mask_config": {
                        "mask_mode": "hybrid"
                    }
                } 
            },

but when I try to run the inpaiting script I get the following error:

 File "/home/sss/Desktop/Palette-Image-to-Image-Diffusion-Models-main/run.py", line 92, in <module>
    main_worker(0, 1, opt)
  File "/home/sss/Desktop/Palette-Image-to-Image-Diffusion-Models-main/run.py", line 37, in main_worker
    phase_loader, val_loader = define_dataloader(phase_logger, opt) # val_loader is None if phase is test.
  File "/home/sss/Desktop/Palette-Image-to-Image-Diffusion-Models-main/data/__init__.py", line 18, in define_dataloader
    phase_dataset, val_dataset = define_dataset(logger, opt)
  File "/home/sss/Desktop/Palette-Image-to-Image-Diffusion-Models-main/data/__init__.py", line 40, in define_dataset
    phase_dataset = init_obj(dataset_opt, logger, default_file_name='data.dataset', init_type='Dataset')
  File "/home/sss/Desktop/Palette-Image-to-Image-Diffusion-Models-main/core/praser.py", line 49, in init_obj
    raise NotImplementedError('{} [{:s}() form {:s}] not recognized.'.format(init_type, class_name, file_name))
NotImplementedError: Dataset [InpaintDataset() form data.dataset] not recognized.

Is there any more step I should do for a successful run? I like to train from the beginning and not use the trained model.

can you guide me, Please?

**Comment by Janspiry** [comment]
1. Since .flist give the image path, 
![image](https://user-images.githubusercontent.com/32922494/193620405-225b2737-bc61-493d-a4cd-68a2e41bc510.png)
and you need to change it yours, e.g.  data/celeba_hq/16587.jpg
2. Could you show me the traceback error?

**Comment by hodfa840** [comment]
Hi,
Here is the trace back:
![Screenshot from 2022-10-03 17-56-14](https://user-images.githubusercontent.com/78338247/193623003-0936bd6a-4c8a-48e2-a271-9766c0b90739.png)

**Comment by hodfa840** [comment]
Hello,
thanks a lot,
 I forgot to rename it!!!
It is solved now.
