### ISSUE TITLE
Recommended Learning Rate for Colorization

### ISSUE THREAD

**Issue by itoshiyanazawa** [Janspiry/Palette-Image-to-Image-Diffusion-Models#48]
Hi!
Currently, I trained colorization model based on this repo and my own dataset which contains 1325 images. Training results were strange, so I want to improve my model.

My current training situation is as follows:

- Training time: 40 hours
- epoch: 1090
- inters: 1439228
- training_mse: 0.004237050597690872

According to the other issues, causes of poor result are lack of dataset or learning rate. Considering dataset, I will use Places2 to have enough dataset.

The things I want to know the most is managing learning rate. In "Pallete" paper, it did not change any parameters, so I would like to know the specific parameters for colorization.

**My tested result**
![Out_00002](https://user-images.githubusercontent.com/67773604/193967354-588ca51e-777f-41ae-96b9-4099236da456.jpg)
![Out_00004](https://user-images.githubusercontent.com/67773604/193967457-9fc8c571-c3e8-45bc-8383-301f28ba6bdf.jpg)

**Comment by Janspiry** [comment]
Just use the preset parameters
