### ISSUE TITLE
Cannot run the test script

### ISSUE THREAD

**Issue by Hans1984** [Janspiry/Palette-Image-to-Image-Diffusion-Models#5]
Hi, thanks for the nice work. However, when I try to run the test scripts, it failed, 
_**NotImplementedError: Model [Palette() form models.model] not recognized.**_
I use the checkpoints and state file you provide. 
Do you know what's the problem? 
Thanks a lot.

**Comment by Janspiry** [comment]
This may be caused by some steps of loading the model, can you give more error messages in console and logs?

**Comment by Hans1984** [comment]
Thanks for your reply, the error goes like this,

  **_### File "run.py", line 103, in <module>
    main_worker(0, 1, opt)
  File "run.py", line 63, in main_worker
    writer = phase_writer
  File "/HPS/BRDF/work/chao/Palette-Image-to-Image-Diffusion-Models/models/__init__.py", line 11, in create_model
    model = init_obj(model_opt, logger, default_file_name='models.model', init_type='Model')
  File "/HPS/BRDF/work/chao/Palette-Image-to-Image-Diffusion-Models/core/praser.py", line 49, in init_obj
    raise NotImplementedError('{} [{:s}() form {:s}] not recognized.'.format(init_type, class_name, file_name))
NotImplementedError: Model [Palette() form models.model] not recognized._**

I also think it was caused by the load pre-trained model since when I do training, it works.

**Comment by Janspiry** [comment]
It will generate some log file such as tests.log experiments dir.
Also I see that this error occurs when the model is initialized and not yet loading, are these the only errors in the full stack trace?

**Comment by Hans1984** [comment]
This is the log file,

_**22-05-18 10:22:08.193 - INFO: Create the log file in directory experiments/test_inpainting_celebahq_220518_102207.

22-05-18 10:22:08.665 - INFO: Dataset [InpaintDataset() form data.dataset] is created.
22-05-18 10:22:08.665 - INFO: Dataset for test have 2000 samples.
22-05-18 10:22:09.207 - INFO: Network [Network() form models.network] is created.
22-05-18 10:22:09.207 - INFO: Config is a str, converts to a dict {'name': 'mae'}
22-05-18 10:22:09.950 - INFO: Metric [mae() form models.metric] is created.
22-05-18 10:22:09.950 - INFO: Config is a str, converts to a dict {'name': 'mse_loss'}
22-05-18 10:22:09.979 - INFO: Loss [mse_loss() form models.loss] is created.
22-05-18 10:22:09.987 - INFO: Optimizer [Adam() form default file] is created.
22-05-18 10:22:09.987 - INFO: Option is None when initialize Scheduler
22-05-18 10:22:13.460 - INFO: Loading pretrained model from [experiments/train_inpainting_celebahq_220426_233652/checkpoint/200_Network.pth] ...**_
Thanks!

**Comment by Janspiry** [comment]
![image](https://user-images.githubusercontent.com/32922494/168993399-03a826b1-55b8-4d07-9cd9-ffa2a9aa0d72.png)
Did you create this folder to save your checkpoint? Otherwise you need to change it.


![image](https://user-images.githubusercontent.com/32922494/168993765-0563a735-a35a-468e-8b36-ea4bccf1578b.png)
And you can note the EMA section, as we do not provide the relevant model.

**Comment by Hans1984** [comment]
Thanks! 
After using the absolute path and commenting out the EMA section, it works well. Awesome!

**Comment by sgbaird** [comment]
@Hans1984 could you elaborate on what you did to address this error?

**Comment by Hans1984** [comment]
Hi, you need to set the EMA as False or comment on the related scripts, because the provided weights were trained without EMA. In addition, pls check the checkpoint's name.

**Comment by sgbaird** [comment]
@Hans1984 Ah gotcha, so I take it that doesn't apply if you're training from scratch, right?

**Comment by Hans1984** [comment]
True, it should be fine if you train from scratch :)

**Comment by lskdream** [comment]
> ![image](https://user-images.githubusercontent.com/32922494/168993399-03a826b1-55b8-4d07-9cd9-ffa2a9aa0d72.png) Did you create this folder to save your checkpoint? Otherwise you need to change it.
> 
> ![image](https://user-images.githubusercontent.com/32922494/168993765-0563a735-a35a-468e-8b36-ea4bccf1578b.png) And you can note the EMA section, as we do not provide the relevant model.

Hi Janspiry, I noticed that in the up-to-date version of code, the last line of code

`self.resume_training([self.optG], self.schedulers)`

doesn't exist.

Shall I add this line of code by myself?
However, after adding it, I got a code error

`AttributeError: 'Palette' object has no attribute 'optG'`
