### ISSUE TITLE
Question about the code of diffusion 

### ISSUE THREAD

**Issue by Luchixiang** [Janspiry/Palette-Image-to-Image-Diffusion-Models#50]
Hi! Thank you for the awesome code. I have one question. 
When calculating the sample_gamma for q-sample. What's the purpose of line 111 in the screenshot.
I think the formula of DDPM is sample_gamma = extract(self.gammas, t, x_shape=(1, 1))
Thank you

<img width="888" alt="image" src="https://user-images.githubusercontent.com/35992729/194701056-9705d652-f717-4e52-9ca7-b7069e0eea97.png">

**Comment by Janspiry** [comment]
Theoretically, yes, I followed the “Image Super-Resolution via Iterative Refinement” setting here
![image](https://user-images.githubusercontent.com/32922494/194711381-2065c078-4a22-449a-8316-b5f72ed793a3.png)

**Comment by Luchixiang** [comment]
Got it! Thanks
