### ISSUE TITLE
About the linear schedule

### ISSUE THREAD

**Issue by Inosonnia** [Janspiry/Palette-Image-to-Image-Diffusion-Models#51]
Thanks for your nice code.

In the implementation details of the paper,  the schedules of training / testing are different: (1e-6, 0.01)  vs. (1e-4, 0.09).

Is there any reason for this setting?  Intuitively we could achieve better and aligned result with a same schedule.
I notice that (1e-4, 0.09) performs better than (1e-6, 0.01) in a number of cases.

**Comment by Janspiry** [comment]
![image](https://user-images.githubusercontent.com/32922494/194711657-5cad8f7b-58a9-46ea-bd51-9a6003ba09a7.png)
Sorry, I did not know the exact answer to this question, and maybe you find somethings in its reference.
