### ISSUE TITLE
Iterations used to train the pre-trained models

### ISSUE THREAD

**Issue by primecai** [Janspiry/Palette-Image-to-Image-Diffusion-Models#52]
Hi,

Many thanks for this repo---it is of great help!
I'm wondering what the iterations used to train the pre-trained models specify? It seems I can reach, e.g. 660k iterations as specified in train.log in less than a day, but my models do not perform nearly as well as the pretrained Place2 inpainting model.
It will be very helpful if there is any training log saved while training the pretrained model, as an early reference and assessment of whether my trainings are likely to work at all.

Best regards,
Shengqu

**Comment by Janspiry** [comment]
Hi, it also depend on your batch_size and gpu nums. You need to scale the appropriate amount to reach the final number of iterations (GPU\*Bs\*Iterations).
![image](https://user-images.githubusercontent.com/32922494/195254290-a758fe43-bd3a-4dfd-83d4-5d03d4bed538.png)

**Comment by primecai** [comment]
Hi,

Many thanks for the quick reply. So for the case of Places2 pre-trained model, the output 'iters' in 'train.log' should actually be 4 * 10 * 660k = 26400k iteration?

Best regards,
Shengqu

**Comment by Janspiry** [comment]
Exactly

**Comment by primecai** [comment]
Many thanks again. May I also ask from what point the model starts to inpaint some very reasonable outputs?

Best regards,
Shengqu

**Comment by Janspiry** [comment]
This needs to be late in training
