### ISSUE TITLE
Is JPEG restoration supported through this implementation?

### ISSUE THREAD

**Issue by sgbaird** [Janspiry/Palette-Image-to-Image-Diffusion-Models#6]
As a side note, do you know if JPEG restoration has the same input and output sizes? Or is it more like the super-resolution task?

**Comment by HeChengHui** [comment]
Hi, curious if there is a script to try out image restoration?

**Comment by Janspiry** [comment]
> Hi, curious if there is a script to try out image restoration?

Hi, no off-the-shelf for now
