### ISSUE TITLE
Inference without ground truth image for inpainting task

### ISSUE THREAD

**Issue by vinodrajendran001** [Janspiry/Palette-Image-to-Image-Diffusion-Models#60]
In my **inpainting** case, during the inference only the  ```y_cond``` and ```mask``` images are given. In that case, may I know  how to do a inference?

In the ```network.py``` script, for the inpainting task the below line will be executed as part of the ```restoration``` function. As ```y_0``` is None for me, I am not sure how to deal with this line. If I skip the below line then the results are very bad (just only some whitish kind of image is generated). Also, in the ```Process.png``` image I can notice that for each step the noise level is increasing rather than decreasing.

```
if mask is not None:
    y_t = y_0*(1.-mask) + mask*y_t
```

**Comment by vinodrajendran001** [comment]
@Janspiry Can you pls advise me on this issue? Many thanks

**Comment by zacsun** [comment]
@vinodrajendran001 I hope the snippet at the bottom of https://github.com/Janspiry/Palette-Image-to-Image-Diffusion-Models/issues/17 helps you, let me know if you need more help on this :)

**Comment by Janspiry** [comment]
> 

@vinodrajendran001, Sorry for late reply, GT is not needed during the reference process. And y_0 is nosie and mask_image in the inference.
And also thanks for @zacsun awesome script!!

**Comment by gitouni** [comment]
@vinodrajendran001 Hi, guy, have you resolved this issue? I think some necessary modifications need to be taken on this code, especially on the setting of `y_0`. For example, when I overlay white dots on the ground-truth image and set it as `gt_image`, the inpainting model cannot output any plausible images anymore. In other words, the output image heavily hinges on the original pixels under the masks. Do you think it is a correct implementation?
![Process_Mask_0001](https://github.com/Janspiry/Palette-Image-to-Image-Diffusion-Models/assets/30369762/569eb2b8-e135-4853-8b9d-53ba07f86566)
