### ISSUE TITLE
Different process between validation and test period

### ISSUE THREAD

**Issue by cszy98** [Janspiry/Palette-Image-to-Image-Diffusion-Models#61]
Hi, Thank you for your good job.
I have trained the model on the FFHQ dataset to restore images that are compressed by JPEG.  During inference and test, it takes the low-quality images as conditional input and y_t.  The validation process works well, while the test process behaves differently. 
Validation:
![image](https://user-images.githubusercontent.com/24344135/201822249-843f8438-44a1-4fa8-b985-ace7ecd10014.png)
Test
![image](https://user-images.githubusercontent.com/24344135/201822284-7c2009b0-4e50-4ba8-8234-c6870591e7d0.png)
I have checked the code and it seems that the model does use the conditional input(compressed images) as the starting $y_t$.

When testing, it looked as if it all started with random noise. So why do they behave inconsistently? is this normal? 
By the way, I found some of the processed images have changed tone, do you know any way to fix this?

**Comment by cszy98** [comment]
The reason is that the timesteps during training and testing are not the same.

**Comment by Kazusa853** [comment]
hello,I‘m sorry to bother you,when i train this model on my own dataset,i have the same problem as yours, I found some of the processed images have changed tone,do you solve this problem now?

**Comment by jingfantan** [comment]
hello,I‘m sorry to bother you,when i train this model on my own dataset,i have the same problem as yours, I found some of the processed images have changed tone,do you solve this problem now?
and you mentioned that  during inference and test, it takes the low-quality images as conditional input and y_t,but how do you set conditional input and y_t during train.
Looking forward to your replay.
