### ISSUE TITLE
Training on my own denoise dataset

### ISSUE THREAD

**Issue by kaneyxx** [Janspiry/Palette-Image-to-Image-Diffusion-Models#62]
Hi there, at first gotta appreciate this amazing implementation!

Here's the question:
I'm one dataset containing the original images and noised ones. I want to train a diffusion models that can denoise the noised image while inference phase. I assume this is another image-to-image translation task. How can I use your script to train this model?
Another question is:
Due to the sampling random Gaussian noise vector at the beginning of inference. Can I always fix that if I just want to denoise the image?

Thanks a lot!!

**Comment by Janspiry** [comment]
It is possible, but it all requires you to understand the training process code. Then for each problem, I understand that you need to：
1. modify the mask image to a noisy image
2. sample from the noisy image instead of the random noise
