### ISSUE TITLE
Training on custom dataset

### ISSUE THREAD

**Issue by morteza89** [Janspiry/Palette-Image-to-Image-Diffusion-Models#65]
Hi, 

To train the model from scratch for uncropping mode on our own dataset, do we need to set our network label in load_everything function of model.py, I mean the following setup:
netG_label = self.netG.__class__.__name__
self.load_network(network=self.netG, network_label=netG_label, strict=False)

Thanks,

**Comment by Janspiry** [comment]
This is unnecessary

**Comment by devshaww** [comment]
> Hi,
> 
> To train the model from scratch for uncropping mode on our own dataset, do we need to set our network label in load_everything function of model.py, I mean the following setup: netG_label = self.netG.**class**.**name** self.load_network(network=self.netG, network_label=netG_label, strict=False)
> 
> Thanks,

Have you trained successfully on your own dataset? I'm wondering how to do that so if you could reply it'd be of great help.
