### ISSUE TITLE
Cannot reproduce uncropping result showing in readme

### ISSUE THREAD

**Issue by rayleichenxi** [Janspiry/Palette-Image-to-Image-Diffusion-Models#69]
Hi~ Thank you very much for sharing your code, it's a great job!

I tried to use the [opensourced inpainting model](https://drive.google.com/drive/folders/1Vz_HC0LcpV6yMLOd-SXyoaqJHtxyPBxZ?usp=sharing) pretrained in Places2 to test uncropping task with some images shared in [google driver](https://drive.google.com/drive/folders/1tC3B8ayaadhXAJrOCTrw15R8t84REPWJ?usp=sharing)；however, my reproduced uncropping result is worse than the results showing in readme and google driver. Here are some of my questions.

1. I wonder, when testing in uncropping task, which model were you use? Is the opensourced inpainting model, or other model trained in uncropping dataset?  

2. And I noticed that, the centering mask results and uncropping results in places2 were tested by model with different training epoches. Are they just the different weights in the same training process, or different models trained with different data process method?

3. If you have the plan to opensource the uncropping pretrained model

Here are some of my reproduced result(in right side) compared with result shared in google driver(in the middle) and GT images (in left side)
![image](https://user-images.githubusercontent.com/81690791/219583769-ebe6102a-371c-4275-949a-fa4587e763cb.png)
![image](https://user-images.githubusercontent.com/81690791/219584704-56907332-17f7-4644-94e7-d15e30bb1646.png)

Looking forward for you reply, thank you!

**Comment by Janspiry** [comment]
Thank you for your attention.
1. I used the uncropping model trained on Places2. Since the model did not converge completely, I did not publish it.
2. The latter. uncropping has a larger range of missing, requiring more iterations.
3. Not yet
