### ISSUE TITLE
What should I modify if I use grayscale image dataset which has only 1 channel?

### ISSUE THREAD

**Issue by devshaww** [Janspiry/Palette-Image-to-Image-Diffusion-Models#70]
I have a dataset of about 1700 txts, which will be converted to tensor of size (h,w,1) like a grayscale image.
When running the program, error below prompted. So I have to modify something.
<img width="562" alt="image" src="https://user-images.githubusercontent.com/22312553/221504408-98f5bc2a-3d6c-4282-a444-16bdafa95a16.png">

Actually I don't know why the UNet has 6 in_channel  and 3 out_channel, normally when dealing with RGB image, it should have 3 in_channel and 3 out_channel.

Can somebody guide me a little bit?
Many thanks!

**Comment by aleksmirosh** [comment]
Hi, 

> I have a dataset of about 1700 txts, which will be converted to tensor of size (h,w,1) like a grayscale image. When running the program, error below prompted. So I have to modify something. <img alt="image" width="562" src="https://user-images.githubusercontent.com/22312553/221504408-98f5bc2a-3d6c-4282-a444-16bdafa95a16.png">
> 
> Actually I don't know why the UNet has 6 in_channel and 3 out_channel, normally when dealing with RGB image, it should have 3 in_channel and 3 out_channel.
> 
> Can somebody guide me a little bit? Many thanks!

Hi, did you fix this? I have the problem with 1channel too.
So, also maybe 6channel here mean - original image + masked_image

**Comment by devshaww** [comment]
I'm using grayscale image, so I just changed in_channel to 2 and out_channel to 1 and it worked.

**Comment by devshaww** [comment]
> Hi,
> 
> > I have a dataset of about 1700 txts, which will be converted to tensor of size (h,w,1) like a grayscale image. When running the program, error below prompted. So I have to modify something. <img alt="image" width="562" src="https://user-images.githubusercontent.com/22312553/221504408-98f5bc2a-3d6c-4282-a444-16bdafa95a16.png">
> > Actually I don't know why the UNet has 6 in_channel and 3 out_channel, normally when dealing with RGB image, it should have 3 in_channel and 3 out_channel.
> > Can somebody guide me a little bit? Many thanks!
> 
> Hi, did you fix this? I have the problem with 1channel too. So, also maybe 6channel here mean - original image + masked_image

I'm using grayscale image, so I just changed in_channel to 2 and out_channel to 1 and it worked.
