### ISSUE TITLE
use specific mask

### ISSUE THREAD

**Issue by ooochen-30** [Janspiry/Palette-Image-to-Image-Diffusion-Models#78]
i want to train a model that use specific mask. i design mask for each image and add new mask_mode in InpaintDataset.get_mask() i import these mask by filepath. but i meet the problem that val/mae is always nan.
warn : nan or inf in input tensor. 
can anyone tell me how to solve this problem ? thanks much

**Comment by Janspiry** [comment]
You can visualize your mask to see if it is consistent with the default format.

**Comment by ooochen-30** [comment]
> You can visualize your mask to see if it is consistent with the default format.

thanks for your reply, i have catched my error and fix it

**Comment by Janspiry** [comment]
You're welcome, feel free to reopen this issue if any questions
