### ISSUE TITLE
How to train colorization?

### ISSUE THREAD

**Issue by mikio303** [Janspiry/Palette-Image-to-Image-Diffusion-Models#8]
Hello, I'm considering to conduct a research about colorization, but I don't know how to train.
How can I train for colorization?
Can I train colorization by changing the code you mentioned in READ.me?

`"which_dataset": {  // import designated dataset using arguments 
    "name": ["data.dataset", "InpaintDataset"], // import Dataset() class
    "args":{ // arguments to initialize dataset
    	"data_root": "your data path",
    	"data_len": -1,
    	"mask_mode": "hybrid"
    } 
},`

**Comment by Janspiry** [comment]
We just test the code in a mini-dataset  https://www.kaggle.com/shravankumar9892/image-colorization. If you want to use this:
1. Download the dataset and use the preprocess script to create flists and images by changing paths in https://github.com/Janspiry/Palette-Image-to-Image-Diffusion-Models/blob/c39ab28bd04d097ad353246dc81f691a4517a62d/preprocess/mirflickr25k_preprocess.py#L33
2. Use the corresponding configure file, that is config/colorization_mirflickr25k.json, and change the flist and image path https://github.com/Janspiry/Palette-Image-to-Image-Diffusion-Models/blob/c39ab28bd04d097ad353246dc81f691a4517a62d/config/colorization_mirflickr25k.json#L49 to point those you set in step 1.
3. Other steps are no different from Inpainting.

**Comment by mikio303** [comment]
Thank you for your reply.
I'll try it!

**Comment by mikio303** [comment]
Thank you for your rapid support! 
By the way, I have another question about evaluation.

Does this model evaluate image by FID ?

**Comment by gabriel-nkole** [comment]
> We just test the code in a mini-dataset https://www.kaggle.com/shravankumar9892/image-colorization. If you want to use this:
> 
> 1. Download the dataset and use the preprocess script to create flists and images by changing paths in https://github.com/Janspiry/Palette-Image-to-Image-Diffusion-Models/blob/c39ab28bd04d097ad353246dc81f691a4517a62d/preprocess/mirflickr25k_preprocess.py#L33
> 2. Use the corresponding configure file, that is config/colorization_mirflickr25k.json, and change the flist and image path https://github.com/Janspiry/Palette-Image-to-Image-Diffusion-Models/blob/c39ab28bd04d097ad353246dc81f691a4517a62d/config/colorization_mirflickr25k.json#L49
>     to point those you set in step 1.
> 3. Other steps are no different from Inpainting.

For step 2, how exactly are the paths specified? In 'data' I created a folder 'datasets' and (after preprocessing) put the 'mirflickr25k' folder in it so that it's consistent with the default 'config/colorization_mirflickr25k.json' file. However, the code still does not work for me. I have tried changing the location and name of the dataset and editing the paths to be relative but it seems the dataset is still not being found by the code.
