### ISSUE TITLE
Question about encode the gama rather than t

### ISSUE THREAD

**Issue by meidachen** [Janspiry/Palette-Image-to-Image-Diffusion-Models#80]
Thank you for open source such a nice code! I have a quick question that hope you could help me with. I'm wondering why you encode the gama rather than t? and why using sample_gammas between gama-t1 (gama t-1) and gama-t2 (gama t) instead of using gama at t?

Thank you in advance for your help!

**Comment by Janspiry** [comment]
This follows the settings of its predecessor, which you can find in Image Super-Resolution via Iterative Refinement.
![image](https://github.com/Janspiry/Palette-Image-to-Image-Diffusion-Models/assets/32922494/f238732e-f0df-4f8b-ac89-539fe60d7ac1)

**Comment by meidachen** [comment]
Thank you, this is very helpful!
