### ISSUE TITLE
How to train for removing photo blur

### ISSUE THREAD

**Issue by cyprian** [Janspiry/Palette-Image-to-Image-Diffusion-Models#9]
Thank you for the awesome work and detailed documentation. 

How would I go about creating a model to remove photo blur?
I want to remove blur from macro photos of flowers. I have a dataset of sharp macro photos.
Could I use any of the existing configs like ex. colorization or would I have to crate a completely new config for this task?

**Comment by Janspiry** [comment]
Theoretically, it is possible, that you can input the incomplete images into the model as a condition, just like super-resolution  or colorization.
You maybe read the colorization config and change it for your task.
